spring:
  application:
    name: COMPARUS interview


application:
  apiPrefix: /api
  openapi:
    dev-url: http://localhost:8080
    prod-url: n/a
#    data sources config. See IT tests config example
